 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/property_features", type: :request do
  
  # PropertyFeature. As you add validations to PropertyFeature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PropertyFeature.create! valid_attributes
      get property_features_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      property_feature = PropertyFeature.create! valid_attributes
      get property_feature_url(property_feature)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_property_feature_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      property_feature = PropertyFeature.create! valid_attributes
      get edit_property_feature_url(property_feature)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PropertyFeature" do
        expect {
          post property_features_url, params: { property_feature: valid_attributes }
        }.to change(PropertyFeature, :count).by(1)
      end

      it "redirects to the created property_feature" do
        post property_features_url, params: { property_feature: valid_attributes }
        expect(response).to redirect_to(property_feature_url(PropertyFeature.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PropertyFeature" do
        expect {
          post property_features_url, params: { property_feature: invalid_attributes }
        }.to change(PropertyFeature, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post property_features_url, params: { property_feature: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested property_feature" do
        property_feature = PropertyFeature.create! valid_attributes
        patch property_feature_url(property_feature), params: { property_feature: new_attributes }
        property_feature.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the property_feature" do
        property_feature = PropertyFeature.create! valid_attributes
        patch property_feature_url(property_feature), params: { property_feature: new_attributes }
        property_feature.reload
        expect(response).to redirect_to(property_feature_url(property_feature))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        property_feature = PropertyFeature.create! valid_attributes
        patch property_feature_url(property_feature), params: { property_feature: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested property_feature" do
      property_feature = PropertyFeature.create! valid_attributes
      expect {
        delete property_feature_url(property_feature)
      }.to change(PropertyFeature, :count).by(-1)
    end

    it "redirects to the property_features list" do
      property_feature = PropertyFeature.create! valid_attributes
      delete property_feature_url(property_feature)
      expect(response).to redirect_to(property_features_url)
    end
  end
end
